myproject/myapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'myapp'  # Ustaw nazwę aplikacji

urlpatterns = [
    path('', views.home, name='home'),
    # path('login/', views.login_view, name='login'),
    path('login/', LoginView.as_view(template_name='myapp/login.html'), name='login'),
    path('register/', views.registration_view, name='registration_view'),
    path('logout/', views.logout_view, name='logout'),
    path('panel/', views.panel_view, name='panel'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('delete_image/<int:image_id>/', views.delete_image, name='delete_image'),
    path("reorder_images/", views.reorder_images, name="reorder_images"),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),  # 'myapp' to nazwa Twojej aplikacji
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

# Create your models here.

# class CustomUser(AbstractUser):
#     # Dodaj dodatkowe pola, które chcesz przechowywać w modelu użytkownika
#     avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
#     birth_date = models.DateField(blank=True, null=True)
#     # Inne pola

#     def __str__(self):
#         return self.username
    
# class Image(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)  # Dodaj import User
#     image = models.ImageField(upload_to='images/')

class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

myproject/myapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ImageUploadForm(forms.Form):
    image = forms.ImageField(label='Zdjęcie',  widget=forms.ClearableFileInput(attrs={'accept': 'image/*'}),)

def validate_username(value):
    if not value.isalnum():
        raise ValidationError('Użyj tylko liter i cyfr.')

class RegistrationForm(UserCreationForm):
    confirm_password = forms.CharField(label='Potwierdź hasło', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        labels = {
            'username': 'Nazwa użytkownika',
            'password1': 'Hasło',
            'password2': 'Potwierdź hasło',
        }

        error_messages = {
            'username': {
                'required': 'To pole jest wymagane.',
                'unique': 'Nazwa użytkownika już istnieje. Wybierz inną nazwę.',
                'invalid': 'Nazwa użytkownika może zawierać jedynie litery i cyfry.',
                'max_length': 'Nazwa użytkownika może mieć maksymalnie 150 znaków.',
            },
            'password1': {
                'min_length': 'Hasło musi mieć co najmniej 8 znaków.',
                'password_mismatch': 'Hasła nie pasują do siebie.',
            },
            'password2': {
                'required': 'To pole jest wymagane.',
            },
        }


    # def clean(self):
    #     cleaned_data = super().clean()
    #     password = cleaned_data.get('password')
    #     confirm_password = cleaned_data.get('confirm_password')

    #     if password and confirm_password and password != confirm_password:
    #         raise ValidationError('Hasła nie są identyczne.')

myproject/myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.conf import settings
from .models import Image
from .forms import ImageUploadForm, RegistrationForm
import logging
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView

logger = logging.getLogger(__name__)

def home(request):
    return render(request, 'myapp/home.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('myapp:panel')  # Przekierowanie po udanym zalogowaniu
    else:
        form = AuthenticationForm()
    return render(request, 'myapp/login.html', {'form': form})

# def registration_view(request):
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST, instance=User())
#         if form.is_valid():
#             # Zarejestruj użytkownika lub wykonaj inne operacje
#             form.save()
#             # Przekieruj użytkownika na stronę logowania po udanej rejestracji
#             return redirect('myapp:login')
#     else:
#         form = RegistrationForm()

#     return render(request, 'myapp/registration.html', {'form': form})

def registration_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:login')
    else:
        form = UserCreationForm()

    return render(request, 'myapp/registration.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('myapp:home')  

@login_required
def panel_view(request):
    images = Image.objects.filter(user=request.user)  # Pobieranie wszystkich zdjęć użytkownika

    context = {
        'images': images,
    }

    return render(request, 'myapp/panel.html', context)

@login_required
def upload_image(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            image = form.cleaned_data['image']
            Image.objects.create(user=user, image=image)

            # Logowanie informacji o przesłanym pliku
            logger.info(f"Użytkownik {user.username} przesłał plik: {image}")

    else:
        form = ImageUploadForm()

    images = Image.objects.filter(user=request.user)

    context = {
        'form': form,
        'images': images,
    }

    return render(request, 'myapp/panel.html', context)

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)

    # Upewnij się, że tylko właściciel może usunąć zdjęcie
    if image.user == request.user:
        image.delete()
    
    return redirect('myapp:panel')

@csrf_exempt
def reorder_images(request):
    if request.method == "POST":
        image_order = request.POST.getlist("order[]")  # Odbieranie kolejności zdjęć jako lista
        try:
            for idx, image_id in enumerate(image_order):
                image = Image.objects.get(id=image_id)
                image.order = idx
                image.save()
            return JsonResponse({"message": "Kolejność zaktualizowana poprawnie."})
        except Exception as e:
            return JsonResponse({"message": "Błąd aktualizacji kolejności: " + str(e)}, status=400)
    return JsonResponse({"message": "Błąd aktualizacji kolejności."}, status=400)

myproject/myapp/templates/myapp/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Projektowanie Aplikacji Internetowych Projekt</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'media/site.webmanifest' %}">
</head>
<body>
    <h1 class="title">Projektowanie Aplikacji Internetowych - Projekt</h1>
    <div class="login">
        <img src="https://images.unsplash.com/photo-1484503793037-5c9644d6a80a?q=80&w=2265&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
        <a href="{% url 'myapp:login' %}" class="btn btn1">Zaloguj</a> 
    </div>
    <div class="register">
        <img src="https://images.unsplash.com/photo-1554050857-c84a8abdb5e2?q=80&w=2427&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
        <a href="{% url 'myapp:registration_view' %}" class="btn btn2">Zarejestruj</a>
    </div>
</body>
</html>

myproject/myapp/templates/myapp/login.html
<!-- login.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Logowanie</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'media/site.webmanifest' %}">
</head>
<body>
    <div class="image">
        <img src="https://images.unsplash.com/photo-1536514498073-50e69d39c6cf?q=80&w=2371&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
    </div>
    <div class="login_form">
        <h1>Logowanie</h1>
            <form method="post" action="{% url 'myapp:login' %}">
                {% csrf_token %}
                <label for="username">Nazwa użytkownika:</label>
                <input type="text" id="username" name="username" required><br>
                <label for="password">Hasło:</label>
                <input type="password" id="password" name="password" required><br>
                <button class="btn btn1" type="submit">Zaloguj</button>
            </form>
    </div>
    
</body>
</html>

myproject/myapp/templates/myapp/panel.html
<!DOCTYPE html>
<html>
<head>
    <title>Panel Klienta</title>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Linki do hostowanych zasobów Bootstrap i jQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/panel.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'media/site.webmanifest' %}">
</head>
<body>
    <div class="header-panel">
        <div class="user-panel">
            <div class="user-info">
                <p>Witaj, {{ user.username }}</p>
            </div>
            <button class="toggle-mode dark" onclick="toggleDarkMode()">🌚</button>
            <button class="toggle-mode light" onclick="toggleDarkMode()">🌞</button>
            <div class="logout-button">
                <form method="post" action="{% url 'myapp:logout' %}">
                    {% csrf_token %}
                    <button type="submit">Wyloguj się</button>
                </form>
            </div>
        </div>
    </div>

    <div class="gallery">
        <form method="post" enctype="multipart/form-data" action="{% url 'myapp:upload_image' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="przeslij" type="submit" value="Submit">Prześlij zdjęcie</button>
        </form>
        
        <div class="row">
            {% for image in images %}
            <div class="col-md-4 sortable-image" data-image-id="{{ image.id }}">
                
                    <img src="{{ image.image.url }}" alt="Obraz">
                
                <form method="post" action="{% url 'myapp:delete_image' image.id %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger delete-button">Usuń</button>
                </form>
            </div>
            {% endfor %}
        </div>
        
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="{% static 'js/sort.js' %}"></script>
    <script src="{% static 'js/darkmode.js' %}"></script>
</body>
</html>

myproject/myapp/templates/myapp/registration.html
{% load static %}

<!-- registration.html -->
<!-- <!DOCTYPE html>
<html>
<head>
    <title>Rejestracja</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/regiter.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/validation.js' %}"></script> 
</head>
<body>
    <div class="image">
        <img src="https://images.unsplash.com/photo-1468657988500-aca2be09f4c6?q=80&w=2370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
    </div>
    <div class="register_form">
        <h1>Rejestracja</h1>
        <form method="post">
            {% csrf_token %}
            <div id="error-message" style="color: red;"></div>
            {{ form.as_p }}
            <button class="btn btn1" type="submit">Zarejestruj</button>
        </form>
    </div>
</body>
</html> -->

<!-- 1 ^^^ / 2 vvv -->

<!-- 
<!DOCTYPE html>
<html>
<head>
    <title>Rejestracja</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/regiter.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/validation.js' %}"></script> 
</head>
<body>
    <div class="image">
        <img src="https://images.unsplash.com/photo-1468657988500-aca2be09f4c6?q=80&w=2370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
    </div>
    <div class="register_form">
        <h2>Rejestracja</h2>
            <form method="post" action="{% url 'myapp:registration_view' %}" id="registrationForm">
                {% csrf_token %}
                <div id="error-message" style="color: red;"></div>
                <input type="text" name="username" id="username" required>
                <br>
                <input type="password" name="password" required>
                <br>
                <input type="password" name="confirm_password" required>
                <br>
                <button class="btn btn1" type="submit">Zarejestruj się</button>
            </form>
    </div>
</body>
</html> -->

<!-- registration.html -->
<!-- registration.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Rejestracja</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/regiter.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'media/site.webmanifest' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/validation.js' %}"></script> 
</head>
<body>
    <div class="image">
        <img src="https://images.unsplash.com/photo-1468657988500-aca2be09f4c6?q=80&w=2370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
    </div>
    <div class="register_form">
        <h1>Rejestracja</h1>
        <!-- <form method="post" action="{% url 'myapp:registration_view' %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
                {{ form.username.errors }}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password }}
                {{ form.password.errors }}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label_tag }}
                {{ form.confirm_password }}
                {{ form.confirm_password.errors }}
            </div>
            <button class="btn btn1" type="submit">Zarejestruj</button>
        </form> -->
        <form method="post" action="{% url 'myapp:registration_view' %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button class="btn btn1" type="submit">Zarejestruj</button>
        </form>
    </div>
</body>
</html>